---
  - name: Install ansible requirements for apt module
    apt: name={{item}} update_cache=yes state=latest
    with_items:
    - python-apt
    - apt-transport-https
  - name: Add Debian testing repo
    apt_repository: repo='deb http://httpredir.debian.org/debian/ testing main'
                    state=present update_cache=yes
  - name: Configure APT preferences for Debian stable/testing
    template: src=apt_debian-testing.preferences 
              dest=/etc/apt/preferences.d/apt_debian-testing.pref
              owner=root group=root mode=0644 backup=yes
