oonibackend_package: oonibackend
enable_dns_helper: yes
enable_dns_discovery_helper: yes
enable_http_return_json_headers_helper: yes
enable_tcp_echo_helper: yes
enable_ssl_helper: no
enable_daphn3_helper: yes

dns_resolver_address: "8.8.8.8:53"

http_return_json_headers_port: 57001
tcp_echo_port: 57002
daphn3_port: 57003
dns_port_tcp: 57004
dns_port_udp: 57004
dns_discover_port_tcp: 57005
dns_discover_port_udp: 57005
ssl_port: 57006

enable_bouncer: no
enable_policy: no
archive_dir: /var/spool/ooni/backend/archive
tor_datadir: /var/spool/ooni/backend/tor
bouncer_file: /var/spool/ooni/backend/bouncer.yaml
policy_file: /var/spool/ooni/backend/policy.yaml
deck_dir: /usr/share/ooni/backend/decks
input_dir: /usr/share/ooni/backend/inputs
report_dir: /var/spool/ooni/backend/raw_reports

oonibackend_install_path: /opt/ooni-backend
oonibackend_log_path: /var/log/ooni
oonibackend_conf: /etc/oonibackend.conf
